# -*- coding: utf-8 -*-
"""notebookb2c7c21920(4).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12NkMsBSdHKEkb1iTukaC0TkGWR9_9wCt

пишем ядро

1. Подгружаем yfinance → сырые цены (Open, High, Low, Close, Volume)
2. Рассчитываем признаки (RSI, lri, obv, atr)
3. Создаём целевую переменную (target) — "будет ли рост через N часов"
4. Делим данные (train/test)
5. Обучаем модели
"""

!pip install hmmlearn

import pandas as pd
import numpy as np
import yfinance as yf
from hmmlearn import hmm
import xgboost as xgb

ticker = yf.Ticker("BTC-USD")
data = ticker.history(period="max")

data.head()

"""

*   *open* - цена актива в начале
*   *high* - максимальная цена за весь период
*   *low*  - минималная цена за весь период
*   *close* - цена закрытия
*   *volume* - кол-во едииц актива, проданного за весь период, типо кол-во акций, кол-во криптомонет и тд
*   *dividends* - выплаты акционерам из прибыли компании, только для акций, значение появлятся в делнь выплат
*   *stock splits* - сплиты акций

"""

dota = yf.download("BTC-USD", period="2y", interval='1h')
dota.head()
print(len(dota))

"""Возможно имеет смысл скачать больше данных, не забыть при этом обновить сплиттер

Выбранные метр ики для предсказания:
RSI,
LRI,
OBV,
ATR

нужно будет переписать так, чтобы было без pandas_ta
"""

#import pandas as pd
#import numpy as np

def rsi(dat, period=14): # средний прирост на средний убыток +-
  delta = dat.diff()

  gain = (delta.where(delta > 0, 0))
  loss = (-delta.where(delta < 0, 0))

  avg_gain = gain.rolling(window=period).mean()
  avg_loss = loss.rolling(window=period).mean()

  rs = avg_gain / avg_loss
  rsi = 100 - (100 / (1 + rs))
  rsi[avg_loss == 0] = 100

  return rsi

def obv(close, vol): # определяем поддерживают ли тренд реальные деньги
  obv = [vol[0]]
  for i in range(1, len(close)):
    if close[i] > close[i-1]:
      obv.append(obv[i-1] + vol[i])
    elif close[i] < close[i-1]:
      obv.append(obv[i-1] - vol[i])
    else:
      obv.append(obv[i-1] + 0)
  return obv

def atr(high, low, close, period=14):  # казывает волатильность
  tr1 = high - low
  tr2 = (high - close.shift()).abs()
  tr3 = (low - close.shift()).abs()

  tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)

  atr = tr.rolling(window=period).mean()
  return atr

def feature_eng(dota):
  if isinstance(dota.columns, pd.MultiIndex):
        dota.columns = [col[0].lower() for col in dota.columns]
  else:
        dota.columns = [col.lower() for col in dota.columns]

  dota['rsi'] = rsi(dota['close']) # считаем на close так как это типо итог, закрытие периода
  # dota['lri_final'] = ta.linreg(dota['close'], length=14) обойдемся без линрега
  dota['obv'] = obv(dota['close'], dota['volume'])
  dota['atr'] = atr(dota['high'], dota['low'], dota['close'])
  dota = dota.dropna()
  return dota

dota2 = feature_eng(dota)
dota2.head()
my_feet = ['rsi', 'obv', 'atr']
signes_cols = dota2[my_feet]  # выделили колонки для анализа hmm
signes = signes_cols.values   # получили значения
print(len(dota2), signes.shape)

"""target

"""

price5 = dota2['close'].shift(-24)
ratio = price5/dota2['close'] - 1
dota2['target'] = (ratio > 0.005).astype(int)
print(dota2['target'])

"""expend window split

Пока что 3 мес, потом может будем увеличивать

* Первое обучение: модель учится на первых 168 часах (7 дней)
* Первая проверка: предсказываем следующие 5 часов
* Расширяем окно: добавляем следующие 24 часа (1 день) к обучению
* Вторая проверка: предсказываем следующие 5 часов
* И так далее, пока не закончатся данные
"""

from sklearn.model_selection import TimeSeriesSplit

tscv = TimeSeriesSplit(n_splits=10, test_size=24, gap=0, max_train_size=336)

for fold, (train_id, test_id) in enumerate(tscv.split(dota2)):
    train = dota2.iloc[train_id]  # iloc используем потому что splitter ориентируется на номера строк, iloc как раз
    test = dota2.iloc[test_id]    # позволяет именно по номеру обращаться к строке

    X_train = train.drop('target', axis=1)
    X_test = test.drop('target', axis=1)

    y_train = train['target']
    y_test = test['target']

    print(len(X_test))

"""Модели для решения первой задачи:


1.   XGBoost
2.   HMM
3.   LSTM
4.   Ансамбли Stacking


"""

model1 = xgb.XGBClassifier(n_estimators=100,
    learning_rate=0.1,
    max_depth=5,
    eval_metric='logloss')

model1.fit(X_train, y_train)

proba1 = model1.predict_proba(X_test)
prediction1 = model1.predict(X_test)

print(len(proba1))

from sklearn.preprocessing import MinMaxScaler
model2 = hmm.GaussianHMM(
    n_components=3,           # количество скрытых состояний
    covariance_type='full',   # тип ковариационной матрицы
    n_iter=1000,              # количество итераций EM-алгоритма
    random_state=42,          # для воспроизводимости
    verbose=True
)

scal = MinMaxScaler(feature_range=(-1,1))
scal.fit(X_train[my_feet])

signes_train = scal.transform(X_train[my_feet])
signes_test = scal.transform(X_test[my_feet])

model2.fit(signes_train)
states = model2.predict(signes_test)

anal = []
current_targets = y_test.values
for st in range(3):
    mask = (states == st)    # True там, где модель предсказала состояние 'st'
    avg_rsi = signes[mask, 0].mean()   # посчитали средний rsi, должен быть больше 60%
    groth = current_targets[mask].mean()   # частота роста
    anal.append([avg_rsi, groth])
    anal.append([0, 0.5])

anal_summery = np.array(anal)
print(anal_summery.shape)

"""для тренировки разных эпох

делим данные для LSTM
"""

# обязательно потом увеличить выборку для обучения!!!

import torch
import torch.nn as nn
import numpy as np
from torch.utils.data import DataLoader, TensorDataset

X_train_tuna = X_train.to_numpy()  # преобразовали в numpy массив
X_test_tuna = X_test.to_numpy()
y_train_tuna = y_train.to_numpy()  # преобразовали в numpy массив
y_test_tuna = y_test.to_numpy()

# скалировали данные
X_train_tuna = scal.fit_transform(X_train_tuna)
X_test_tuna = scal.transform(X_test_tuna)

print(X_train_tuna.shape, X_test_tuna.shape, y_train_tuna.shape, y_test_tuna.shape)

lookback = 24  # длина окна
X_train_tuna = X_train_tuna.reshape((-1, lookback, 8))
X_test_tuna = X_test_tuna.reshape((-1, lookback, 8))

def y_create(y, lookback):
  y_my = []
  for i in range(0, len(y)-lookback+1, lookback):
    id = i+lookback - 1 # предсказываем последний час в окне 24 часа!!!!!
    if id< len(y):
      y_my.append(y[id])
  return y_my

y_tr_new = np.array(y_create(y_train_tuna, lookback))
y_te_new = np.array(y_create(y_test_tuna, lookback))

print(X_train_tuna.shape, X_test_tuna.shape, y_tr_new.shape, y_te_new.shape)  # тестовый y очень маленький нужно будет потом потыкаться в диапазоны, чтобы там была норм размерность

X_train_tuna = torch.tensor(X_train_tuna).float()
X_test_tuna = torch.tensor(X_test_tuna).float()
y_tr_new = torch.tensor(y_tr_new).float()
y_te_new = torch.tensor(y_te_new).float()

print(X_train_tuna.shape, X_test_tuna.shape, y_tr_new.shape, y_te_new.shape)


train_dataset = TensorDataset(X_train_tuna, y_tr_new)
test_dataset = TensorDataset(X_test_tuna, y_te_new)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16, shuffle=True)

"""сама модель:"""

class mineLSTM(nn.Module):
  def __init__(self, input_size, hidden_size, num_stack_layers): # input_size= number of feat, hidden_size, num_stack_layers
    super(mineLSTM, self).__init__() # для инициализации модели
    self.hidden_size = hidden_size
    self.num_stack_layers = num_stack_layers

    self.lstm = nn.LSTM(input_size, hidden_size, num_stack_layers, batch_first=True)
    self.fc = nn.Linear(hidden_size, 1)

  def forward(self, x):
    batch_size = x.size(0)
    h0 = torch.zeros(self.num_stack_layers, batch_size, self.hidden_size)
    c0 = torch.zeros(self.num_stack_layers, batch_size, self.hidden_size)

    out,_ = self.lstm(x, (h0, c0))
    out = self.fc(out[:, -1, :])

    return out

def train_one_epoch(model_x):
  model_x.train(True)
  loss_now = 0.0

  for batch_index, batch in enumerate(test_loader):
    x_batch, y_batch = batch[0], batch[1]
    y_batch = y_batch.view(-1, 1).float()

    output = model_x(x_batch)
    loss = loss_fu(output, y_batch)
    loss_now += loss.item()
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


def validate_one_epoch(model_x): # тут мы смотрим какие показатели были у эпохи без смены градиентов
  model_x.train(False)
  loss_now = 0.0

  for batch_index, batch in enumerate(train_loader):
    x_batch, y_batch = batch[0], batch[1]
    y_batch = y_batch.view(-1, 1).float()

    with torch.no_grad():
      output = model_x(x_batch)
      loss = loss_fu(output, y_batch)
      loss_now += loss

  avg_loss = loss_now/len(test_loader)

"""обучаем:"""

model3 = mineLSTM(8, 14, 3) # запустили модель input_size, hidden_size, num_layers
loss_fu = nn.BCEWithLogitsLoss()
learning_rate = 0.001
optimizer = torch.optim.Adam(model3.parameters(), learning_rate)
epochs=50

for epoch in range(epochs):
  train_one_epoch(model3)
  validate_one_epoch(model3)

predictions3 = []
model3.eval()
with torch.no_grad():
  prediction3 = model3(X_train_tuna)
  pred_np = torch.sigmoid(prediction3).detach().numpy().flatten() # сделали numpy массив
  predictions3.append(pred_np)
print(len(pred_np))

"""Ансамблевая модель:"""

from sklearn.linear_model import LogisticRegression

full_pred_ensembl = np.column_stack([proba1, states, pred_np])
meta = LogisticRegression()
meta.fit(full_pred_ensembl, y_test)

meta_pred = meta.predict(X_test)
meta_proba = meta.predict_proba(X_test)[:, 1]

print(meta_proba)

# тут ошибка, потому что пока что для lstm очень мало данных
# когда буду увеличивать диапазон в теории должно запуститься

"""Формула Келли чтобы понять сколько нужно купить

"""

def Kelly(proba, risk_reward, koef=0.5): # типо подаем на вход вероятность роста цены, отношение прибыль/убыток, коефициент сглаживания
  k = (proba - (1-proba)/risk_reward) * koef
  if k<0:
    return 0
  return k

full_pred = np.column_stack([full_pred_ensembl, meta_proba]) # матрица с предсказаниями по массиву, 1 столбкц - 1 модель

for pr1 in full_pred[full_pred[:, 0] > 0.5]: # пробегаемся по первому столбцу, смотрим, что если у него вероятность больше 50 то покупаем
    # вункция для формулы келли и ml решение
    kelly_vibes = Kelly(pr1[0], risk_reward=2)
    pass

for pr3 in full_pred[full_pred[:, 2] > 0.5]: # lstm
    # вункция для формулы келли и ml решение
    kelly_vibes = Kelly(pr3[2], risk_reward=2)
    pass

masochka = ((full_pred[:, 1] > 0.6) & (full_pred[:, 2] > 0)) | ((full_pred[:, 1] < 0.4) & (full_pred[:, 2] > 0))
for pr2 in full_pred[masochka]: # пробегаемся по столбцу с hmm с состояниями рынка
    # вункция для формулы келли и ml решение
    kelly_vibes = Kelly(pr2[1], risk_reward=2)
    pass

for pr4 in full_pred[full_pred[:, 3] > 0.5]: # ensembl
    # вункция для формулы келли и ml решение
    kelly_vibes = Kelly(pr4[3], risk_reward=2)
    pass

